baseurl: "https://qiref.github.io/"
languageCode: "cn-zh"
# defaultContentLanguage: "en"
defaultContentLanguage: "zh"
title: "大道至简"
theme: "hugo-xmin"
googleAnalytics: "G-PGMJFXZJRT"
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

footnotereturnlinkcontents: "↩"
#paginate: 10
#pagination.pagerSize: 10
enableEmoji: true
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: ["HTML", "RSS", "JSON"]

sitemap:
  changeFreq: "daily"
  filename: sitemap.xml
  priority: -1

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Tags
      url: "tags/"
      weight: 2
    - name: About
      url: "about/"
      weight: 3
    - name: Note
      url: "note/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; powered by [Hugo](https://gohugo.io/) & [Xmin](https://github.com/yihui/hugo-xmin)  2017 -- {Year} | [Github](https://github.com/qiref) "

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
